version: "3.8"

services:
  kalkulacka_mysql:
    image: mysql:5.7
    container_name: kalkulacka_mysql
    restart: always
    command: --max_allowed_packet=700M
    environment:
      MYSQL_DATABASE: 'kalkulacka'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3307:3306'
    expose:
      - '3307'
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
